<a href="https://colab.research.google.com/github/wilmanAQ/Inteligencia_Artificial/blob/IA/Clase1_numpy_segundo_corte_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy

NumPy (Numerical Python) es una de las librerías fundamentales para el análisis y manipulación de datos en Python.  
Está diseñada para trabajar con **arrays multidimensionales** y ofrece funciones matemáticas de alto rendimiento, ideales para **cálculo científico, estadística y machine learning**.

En esta clase veremos:
1. ¿Qué es NumPy y por qué usarlo?
2. Creación de arrays.
3. Operaciones básicas.
4. Indexación y slicing.
5. Funciones útiles.
6. Operaciones matemáticas y estadísticas.
7. Ejemplo práctico.

---


In [ ]:
# Instalación (solo si no está instalado)
# En Colab ya viene incluido, pero lo dejamos por si acaso
!pip install numpy

# Importar la librería
import numpy as np

print("Versión de NumPy:", np.__version__)


Versión de NumPy: 2.0.2


## 1. ¿Por qué NumPy?
- Python puro es poco eficiente para cálculos numéricos intensivos.
- NumPy permite trabajar con arrays y matrices de forma **mucho más rápida** que las listas tradicionales.
- Es la base de muchas librerías como Pandas, SciPy, Scikit-Learn, TensorFlow, PyTorch, etc.



- Documentación: https://numpy.org/doc/2.3/user/absolute_beginners.html


# Comparación rápida: listas vs NumPy

# listas

In [1]:
# Comparación rápida: listas vs NumPy
import time

# Lista normal
lista = list(range(10000))
start = time.time()
[ x*2 for x in lista ]
print("Tiempo con lista:", time.time() - start)
print("Proeba:Wilman")

Tiempo con lista: 0.0008089542388916016
Proeba:Wilman


# Array NumPy

In [ ]:
# Array NumPy
arr = np.arange(10000)
start = time.time()
arr * 2
print("Tiempo con NumPy:", time.time() - start)

## 2. Creación de Arrays

Podemos crear arrays de varias formas:
- A partir de listas.
- Usando funciones de NumPy (arange, zeros, ones, linspace).

In [ ]:
# Array a partir de lista
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)

# Array de ceros
arr2 = np.zeros((3,3))
print("\nMatriz de ceros:\n", arr2)

# Array de unos
arr3 = np.ones((2,4))
print("\nMatriz de unos:\n", arr3)

# Rango de números
arr4 = np.arange(0, 10, 2)  # de 0 a 10 con paso de 2
print("\nRango:", arr4)

# Números espaciados
arr5 = np.linspace(0, 1, 5)  # 5 valores entre 0 y 1
print("\nLinspace:", arr5)


Array: [1 2 3 4 5]

Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Rango: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


## 3. Operaciones básicas


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)
print("Potencia:", a ** 2)


Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]
Potencia: [ 100  400  900 1600]


## 4. Indexación y Slicing


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Primer elemento:", arr[0])
print("Último elemento:", arr[-1])
print("Subarray:", arr[1:4])


Primer elemento: 10
Último elemento: 60
Subarray: [20 30 40]


## 5. Funciones útiles


In [ ]:
arr = np.array([3, 6, 9, 12])

print("Suma:", np.sum(arr))
print("Media:", np.mean(arr))
print("Máximo:", np.max(arr))
print("Mínimo:", np.min(arr))
print("Raíz cuadrada:", np.sqrt(arr))


Suma: 30
Media: 7.5
Máximo: 12
Mínimo: 3
Raíz cuadrada: [1.73205081 2.44948974 3.         3.46410162]


## 6. Operaciones con matrices


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Matriz A:\n", A)
print("Matriz B:\n", B)

print("\nSuma:\n", A + B)
print("\nProducto elemento a elemento:\n", A * B)
print("\nProducto matricial:\n", A.dot(B))
print("\nTranspuesta de A:\n", A.T)


Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[2 0]
 [1 3]]

Suma:
 [[3 2]
 [4 7]]

Producto elemento a elemento:
 [[ 2  0]
 [ 3 12]]

Producto matricial:
 [[ 4  6]
 [10 12]]

Transpuesta de A:
 [[1 3]
 [2 4]]


## 7. Ejemplo práctico: Normalización de datos


In [ ]:
datos = np.array([5, 10, 15, 20, 25])

# Normalización Min-Max
normalizados = (datos - np.min(datos)) / (np.max(datos) - np.min(datos))
print("Datos originales:", datos)
print("Datos normalizados:", normalizados)


Datos originales: [ 5 10 15 20 25]
Datos normalizados: [0.   0.25 0.5  0.75 1.  ]
